# 引用公用 gitlab ci 组件，所有项目都需要引用
include:
  - project: "infra/gitlab/gitlab-ci"
    ref: master
    file: "java.yaml"

build:maven:
  extends: .maven

########### x-pai-biz 服务 ###########
## BUILD
# TEST: 当分支为 test 开头时，build 测试 docker 的 docker image
x-pai-biz:build:docker:test:
  extends: .build:docker:test
  variables:
    PROJECT_DIR: x-pai-service
    PROJECT_NAME: x-pai-biz

# PROD: 当分支为 master 且有tag 时， 根据 tag build 镜像
x-pai-biz:build:docker:master:tag:
  extends: .build:docker:master:tag
  variables:
    PROJECT_DIR: x-pai-service
    PROJECT_NAME: x-pai-biz

## DEPLOY
# TEST: 当分支为 test 开头时，可以手动发布项目
x-pai-biz:deploy:test:
  extends: .deploy:test
  variables:
    K8S_CLUSTER: aliyun-prod
    PROJECT_DIR: x-pai-service
    PROJECT_NAME: x-pai-biz


# PROD: 当分支为 master 且有tag 时，可以手动发布项目
x-pai-biz:deploy:production:
  extends: .deploy:production
  variables:
    K8S_CLUSTER: aliyun-prod
    PROJECT_DIR: x-pai-service
    PROJECT_NAME: x-pai-biz

########### x-pai-serving 服务 ###########
## BUILD
# TEST: 当分支为 test 开头时，build 测试 docker 的 docker image
x-pai-serving:build:docker:test:
  extends: .build:docker:test
  variables:
    PROJECT_DIR: x-pai-service
    PROJECT_NAME: x-pai-serving

# PROD: 当分支为 master 且有tag 时， 根据 tag build 镜像
x-pai-serving:build:docker:master:tag:
  extends: .build:docker:master:tag
  variables:
    PROJECT_DIR: x-pai-service
    PROJECT_NAME: x-pai-serving

## DEPLOY
# TEST: 当分支为 test 开头时，可以手动发布项目
x-pai-serving:deploy:test:
  extends: .deploy:test
  variables:
    K8S_CLUSTER: aliyun-prod
    PROJECT_DIR: x-pai-service
    PROJECT_NAME: x-pai-serving

# PROD: 当分支为 master 且有tag 时，可以手动发布项目
x-pai-serving:deploy:production:
  extends: .deploy:production
  variables:
    K8S_CLUSTER: aliyun-prod
    PROJECT_DIR: x-pai-service
    PROJECT_NAME: x-pai-serving

#
### DEPLOY
## TEST: 当分支为 test 开头时，可以手动发布项目
#
# x-pai-engine
x-pai-engine:build:docker:test:
  extends: .build:docker:test
  variables:
    K8S_CLUSTER: aliyun-prod
    PROJECT_DIR: x-pai-engine
    PROJECT_NAME: x-pai-engine
#
x-pai-engine:build:docker:master:tag:
  extends: .build:docker:master:tag
  variables:
    K8S_CLUSTER: aliyun-prod
    PROJECT_DIR: x-pai-engine
    PROJECT_NAME: x-pai-engine
#
x-pai-engine:test:
  extends: .deploy:test
  variables:
    K8S_CLUSTER: aliyun-prod
    PROJECT_DIR: x-pai-engine
    PROJECT_NAME: x-pai-engine

x-pai-engine:production:
  extends: .deploy:production
  variables:
    K8S_CLUSTER: aliyun-prod
    PROJECT_DIR: x-pai-engine
    PROJECT_NAME: x-pai-engine


#ADMIN

# x-pai-engine
pai-admin:build:docker:test:
  extends: .build:docker:test
  variables:
    K8S_CLUSTER: aliyun-prod
    PROJECT_DIR: pai-admin
    PROJECT_NAME: pai-admin

pai-admin:build:docker:master:tag:
  extends: .build:docker:master:tag
  variables:
    K8S_CLUSTER: aliyun-prod
    PROJECT_DIR: pai-admin
    PROJECT_NAME: pai-admin

pai-admin:test:
  extends: .deploy:test
  variables:
    K8S_CLUSTER: aliyun-prod
    PROJECT_DIR: pai-admin
    PROJECT_NAME: pai-admin

pai-admin:production:
  extends: .deploy:production
  variables:
    K8S_CLUSTER: aliyun-prod
    PROJECT_DIR: pai-admin
    PROJECT_NAME: pai-admin
