export enum AppActionTypes {
  ACTION_SET_LANGUAGE = 'ACTION_SET_LANGUAGE',
  ACTION_SET_COLUMN = 'ACTION_SET_COLUMN',
  ACTION_ADD_CACHE_VIEW = 'ACTION_ADD_CACHE_VIEW',
  ACTION_DELETE_CACHE_VIEW = 'ACTION_DELETE_CACHE_VIEW',
}
